apiVersion: apps/v1
kind: Deployment
metadata:
  name: asterra-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asterra-app
  template:
    metadata:
      labels:
        app: asterra-app
    spec:
      serviceAccountName: asterra-app-sa
      containers:
        - name: asterra-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.databaseUrl | quote }}
            - name: S3_BUCKET_NAME
              value: {{ .Values.env.s3Bucket | quote }}