apiVersion: apps/v1
kind: Deployment
metadata:
  name: asterra-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asterra-app
  template:
    metadata:
      labels:
        app: asterra-app
    spec:
      serviceAccountName: asterra-app-sa
      containers:
        - name: asterra-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: {{ .Values.env.databaseUrl | quote }}
            - name: DB_NAME
              value: {{ .Values.env.databaseName | quote }}
            - name: DB_USER
              value: {{ .Values.env.databaseUser | quote }}
            - name: S3_BUCKET
              value: {{ .Values.env.s3Bucket | quote }}
            - name: PGSSLMODE
              value: "disable"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 45
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 15